apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-1
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "110"
      requests:
        cpu: "110"
    args:
    - -cpus
    - "2" # try to use 2 CPU