apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
containers:
  - name: metrics-server
    image: k8s.gcr.io/metrics-server-amd64:v0.3.3
    imagePullPolicy: Always
    args: [ "--kubelet-insecure-tls" ]
    volumeMounts:
    - name: tmp-dir
    mountPath: /tmp