apiVersion: v1
kind: Pod
metadata:
  name: required-anti-affinity
spec:
  affinity:
    podAntiAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
      - labelSelector:
          matchExpressions:
          - key: security 
            operator: In 
            values:
            - S1
            - S2
        topologyKey: kubernetes.io/hostname
  containers:
  - name: required-anti-affinity
    image: docker.io/ocpqe/hello-pod