apiVersion: v1
kind: Pod
metadata:
  name: node-required-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - advanced-scheduling-worker2
  containers:
  - name: node-required-affinity
    image: docker.io/ocpqe/hello-pod