apiVersion: v1
kind: Pod
metadata:
  name: node-preferred-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname 
            operator: In
            values:
            - advanced-scheduling-worker3
  containers:
  - name: node-preferred-affinity
    image: docker.io/ocpqe/hello-pod