apiVersion: v1
kind: Pod
metadata:
  name: preferred-pod-antiaffinity
spec:
  affinity:
    podAffinity: 
      preferredDuringSchedulingIgnoredDuringExecution: 
      - weight: 100  
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security 
              operator: In 
              values:
              - S2
          topologyKey: kubernetes.io/hostname
  containers:
  - name: preferred-pod-affinity
    image: docker.io/ocpqe/hello-pod