apiVersion: v1
kind: Pod
metadata:
  name: required-pod-affinity
spec:
  affinity:
    podAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
      - labelSelector:
          matchExpressions:
          - key: security 
            operator: In 
            values:
            - S1
        topologyKey: kubernetes.io/hostname
  containers:
  - name: required-pod-affinity
    image: docker.io/ocpqe/hello-pod