apiVersion: v1
kind: Pod
metadata:
  name: pod80cpus
spec:
  containers:
  - name: pod80cpus
    image: vish/stress
    resources:
      requests:
        cpu: "80"
      limits:
        cpu: "80"
    args:
    - -cpus
    - "2" # try to use 2 CPU