apiVersion: v1
kind: Pod
metadata:
  name: pod1cpu
spec:
  containers:
  - name: pod1cpu
    image: vish/stress
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "2"
    args:
    - -cpus
    - "2"