apiVersion: v1
kind: Pod
metadata:
  name: ubuntumemory
spec:
  containers:
  - name: ubuntumemory
    image: ubuntu:21.04
    args:
    - sleep
    - "1000000000"
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"